# Generated by Django 3.1.7 on 2021-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Childcare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('approval_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('suburb', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=4)),
                ('overall_rating', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['approval_number', 'name'],
            },
        ),
    ]
